site_name: Lightpack Documentation
nav:
  - Getting Started:
      - Quick Install: install.md
  - Basics:
      - Routing: routing.md
      - Controllers: controllers.md
      - Views: views.md
      - Request: request.md
      - Response: response.md
      - Sessions: sessions.md
      - Cookies: cookies.md
      - Validation: validation.md
      - Filesystem: filesystem.md
      - Configuration: configuration.md
      - Environments: environments.md
      - Date & Time: moment.md
      - Utility Functions: utility-functions.md
  - Databases:
      - Connection: db-connection.md
      - Query Builder: db-query-builder.md
      # - Pagination: db-pagination.md
      - Migrations: migrations.md
      - Seeder: seeder.md
      - Factory: factory.md
  - Lucid ORM:
      - Introduction: orm-introduction.md
      - Models: models.md
      - Relationships: relationships.md
      - Eager Loading: eager-loading.md
      - Collections: collections.md
      - Transformers: transformers.md
  # Security
      # - XSS: more-pages.md
      # - CSRF: custom-navbar.md
      - Authentication:
          - Introduction: authentication.md
          - API Access Tokens: api-access-tokens.md
          - Configuration: auth-configuration.md
          - Extending Auth: custom-auth.md
          - Route Filters: auth-filters.md
  - Utilities:
      - Password: password.md
      - Crypto: encryption-decryption-utils.md
      - URL: url.md
      - Image: image-utils.md
      - Rate Limit: rate-limiter.md
      - Mutex Lock: mutex-lock.md
      - Process: process.md
      - Array: array-utils.md
      - String: string-utils.md
      - OTP: otp-utils.md
      - Assets: asset-loading-utils.md
      - CSV: csv-utils.md
      - PHP to JS: js-utils.md
  - Advanced:
      - Mails: mails.md
      - Queue: queue.md
      - Schedule: schedule.md
      - Filters: filters.md
      - Events: events.md
      - Caching: caching.md
      - Logging: logging.md
      - Providers: providers.md
      - Containers: containers.md
      - CORS: cors.md
      - HTTP Client: http-client.md
      - Console: console.md
      - Testing: testing.md
      - Secrets: secrets.md
      - Settings: settings.md
      - Tags: tags.md
      - Taxonomies: taxonomies.md
      - Faker: faker.md
      - Audit: audit.md
      - RBAC: rbac.md
      - Captcha: captcha.md
      - Webhook: webhook.md
      - AI: ai-service.md
      - Cable: cable.md
      - Uploads: uploads.md
      - Social Auth: social-auth.md
      - SMS: sms.md
      - MFA: mfa.md
      - Storage: storage.md
# Theme
theme:
  name: material
  logo: _media/logo.png  # Place your logo image here
  favicon: _media/logo.png
  palette:
    - scheme: default
      primary: red
      accent: grey
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: grey
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
  font:
    text: Roboto
    code: Fira Mono
  language: en
  highlightjs: true
  highlight_theme: material
  custom_dir: docs/stylesheets
  extra_css:
    - stylesheets/extra.css
# Edit on GitHub
repo_url: https://github.com/lightpack/docs
repo_name: lightpack/docs
edit_uri: edit/main/docs/
# Extra config for TOC and sidebar
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
